apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-app
  name: kafka-svc
spec:
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
    nodePort: 30992
  selector:
    app: kafka-app
  type: NodePort
