apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  labels:
    app: sdn-app
  name: sdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdn-app
  template:
    metadata:
      labels:
        app: sdn-app
    spec:
      containers:
      - env:
        - name: KAFKA_SUBSCRIBER_IP
          value: kafka-svc
        - name: KAFKA_SUBSCRIBER_PORT
          value: '9092'
        - name: KAFKA_PUBLISHER_IP
          value: kafka-svc
        - name: KAFKA_PUBLISHER_PORT
          value: '9092'
        - name: DRPY_IP
          value: oia-pce-svc
        - name: DRPY_PORT
          value: '40000'
        image: tqhuy812/hsdnc-ofc2023:1.1.0
        name: t-sdnc
        stdin: true
        tty: true
