apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdn-app
  name: sdn-svc
spec:
  ports:
  - name: cli
    nodePort: 31002
    port: 8101
    targetPort: 8101
  - name: rest
    nodePort: 30002
    port: 8181
    targetPort: 8181
  selector:
    app: sdn-app
  type: NodePort
