apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oia-pce-app
  name: oia-pce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oia-pce-app
  template:
    metadata:
      labels:
        app: oia-pce-app
    spec:
      containers:
      - env:
        - name: PCE_IP
          value: 0.0.0.0
        image: tqhuy812/drpy
        name: oia-pce
        stdin: true
        tty: true
