apiVersion: v1
kind: Service
metadata:
  labels:
    app: tapi-ui-svc
  name: tapi-ui-svc
spec:
  ports:
  - name: socket-connection
    port: 8000
    targetPort: 8000
    nodePort: 30800
  - name: http-gui
    port: 8001
    targetPort: 8001
    nodePort: 30801
  selector:
    app: tapi-ui-app
  type: NodePort
