apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tapi-ui-app
  name: tapi-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapi-ui-app
  template:
    metadata:
      labels:
        app: tapi-ui-app
    spec:
      containers:
      - image: hthieu/opticalgui:v4.0.0
        name: tapi-ui-app
        stdin: true
        tty: true
        env:
        - name: MONGODB_IP
          value: gui-db-svc
        - name: SDNC_KAFKA_BROKER_IP 
          value: kafka-svc
        - name: SDNC_KAFKA_BROKER_PORT
          value: "9092"



#docker run -dit -p 8000:8000 -p 8001:8001 --name=gui -e MONGODB_IP=10.5.3.104 hthieu/opticalgui:v4.0.0